import { pgTable, text, real, integer, boolean, jsonb, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const sessionsTable = pgTable("sessions", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id").notNull(),
  sessionId: text("session_id").notNull(),
  fingerprintHash: text("fingerprint_hash"),
  ip: text("ip"),
  country: text("country"),
  city: text("city"),
  timezone: text("timezone"),
  source: text("source").notNull().default("direct"),
  medium: text("medium"),
  campaign: text("campaign"),
  adSet: text("ad_set"),
  deviceType: text("device_type"),
  os: text("os"),
  browser: text("browser"),
  ua: text("ua"),
  siteId: text("site_id"),
  landingPage: text("landing_page"),
  classification: text("classification").notNull().default("trusted"),
  fraudScore: real("fraud_score").notNull().default(0),
  trustScore: real("trust_score").notNull().default(100),
  confidence: real("confidence").notNull().default(0.9),
  action: text("action").notNull().default("observe"),
  humanScore: real("human_score"),
  humanConfidence: real("human_confidence"),
  humanClassification: text("human_classification"),
  humanDecision: text("human_decision"),
  browserIntegrityScore: real("browser_integrity_score"),
  behaviorScore: real("behavior_score"),
  deviceConsistencyScore: real("device_consistency_score"),
  networkScore: real("network_score"),
  historicalScore: real("historical_score"),
  // Traffic Intelligence Engine (TIEg)
  trafficTrustScore: real("traffic_trust_score"),
  trafficQualityScore: real("traffic_quality_score"),
  trafficFraudScore: real("traffic_fraud_score"),
  trafficConfidence: real("traffic_confidence"),
  trafficRiskTier: text("traffic_risk_tier"),
  trafficDecision: text("traffic_decision"),
  trafficSourceScore: real("traffic_source_score"),
  trafficCampaignScore: real("traffic_campaign_score"),
  trafficEngagementScore: real("traffic_engagement_score"),
  trafficConversionScore: real("traffic_conversion_score"),
  trafficReferralScore: real("traffic_referral_score"),
  trafficGeoScore: real("traffic_geo_score"),
  trafficTemporalScore: real("traffic_temporal_score"),
  trafficDeviceNetworkScore: real("traffic_device_network_score"),
  manualOverride: boolean("manual_override").default(false),
  reasonCodes: jsonb("reason_codes").$type<string[]>().default([]),
  cost: real("cost").default(0),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertSessionSchema = createInsertSchema(sessionsTable).omit({ createdAt: true, updatedAt: true });
export type InsertSession = z.infer<typeof insertSessionSchema>;
export type Session = typeof sessionsTable.$inferSelect;
